### ISSUE TITLE
[recommandation] Gravatard

### ISSUE THREAD

**Issue by Fr-Dae** [MrFastZombie/AsphaltRoadsPatched#6]
hello, can i suggest you to add your avatard on gravard because you look like very "noname" on github/gitkraken
![Capture d’écran du 2024-12-07 14-53-14](https://github.com/user-attachments/assets/fd2d3469-863a-44ba-b501-a466813fed9b)

**Comment by MrFastZombie** [comment]
I do have a Gravatar account, but because I use an anonymized Github email address on my commits I can't modify the Gravatar for them. Other tools (i.e. Fork) seem to get around this by just pulling the GitHub account avatar, but GitKraken appears to not do this.
